# Generated by Django 6.0.1 on 2026-09-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('revenu', 'Revenu'), ('depense', 'Dépense')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_emission', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payee', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='Comptes.ferme')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('revenu', 'Revenu'), ('depense', 'Dépense')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Comptabilite.categorietransaction')),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Comptes.ferme')),
            ],
        ),
    ]
