# Generated by Django 6.0.1 on 2026-09-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bassin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=50)),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bassins', to='Comptes.ferme')),
            ],
        ),
        migrations.CreateModel(
            name='Poisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espece', models.CharField(max_length=50)),
                ('date_ensemencement', models.DateField()),
                ('poids_moyen', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bassin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poissons', to='Psciculture.bassin')),
            ],
        ),
        migrations.CreateModel(
            name='QualiteEau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateTimeField(auto_now_add=True)),
                ('ph', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('oxygene', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bassin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures_qualite', to='Psciculture.bassin')),
            ],
        ),
    ]
