# Generated by Django 6.0.1 on 2026-09-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('formation', 'Formation'), ('vente', 'Vente'), ('stage', 'Stage'), ('recrutement', 'Recrutement'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('lieu', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='Carrieres.offre')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
