# Generated by Django 6.0.1 on 2026-09-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrieres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='lu',
        ),
        migrations.AddField(
            model_name='candidature',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='candidatures/cv/'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours d’examen'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='nouveau', max_length=20),
        ),
    ]
