# Generated by Django 6.0.1 on 2026-09-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espece', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('poids', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_naissance', models.DateField()),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animaux', to='Comptes.ferme')),
            ],
        ),
        migrations.CreateModel(
            name='SanteAnimale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField()),
                ('diagnostic', models.TextField()),
                ('traitement', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites_sante', to='Elevage.animal')),
            ],
        ),
    ]
