# Generated by Django 6.0.1 on 2026-09-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_application', models.CharField(default='CPAM', max_length=150)),
                ('slogan', models.CharField(blank=True, default='Centre de Production Agricole et Multi-ressources', max_length=255)),
                ('description', models.TextField(blank=True, default="Plateforme intégrée de gestion agricole, d'élevage et de pisciculture.")),
                ('logo_url', models.TextField(blank=True, default='')),
                ('email_contact', models.EmailField(blank=True, default='contact@cpam.com', max_length=254)),
                ('telephone', models.CharField(blank=True, default='+223 70 00 00 00', max_length=50)),
                ('adresse', models.CharField(blank=True, default='Bamako, Mali', max_length=255)),
                ('devise', models.CharField(blank=True, default='FCFA', max_length=10)),
                ('site_web', models.URLField(blank=True, default='')),
                ('facebook', models.CharField(blank=True, default='', max_length=255)),
                ('linkedin', models.CharField(blank=True, default='', max_length=255)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
