# Generated by Django 6.0.1 on 2026-09-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('saison', models.CharField(max_length=50)),
                ('sol_requis', models.CharField(max_length=100)),
                ('rendement_moyen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_plantation', models.DateField()),
                ('date_recolte', models.DateField()),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='Comptes.ferme')),
            ],
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigations', to='Agriculture.culture')),
            ],
        ),
    ]
